name: rebook
description: "Recycling Guide Application"

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  #Default
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: any

  # Icons
  cupertino_icons: ^1.0.6

  # Splash Screen
  flutter_native_splash: ^2.4.0

  # Dotenv
  flutter_dotenv: ^5.1.0

  # Localization And Logger
  intl: ^0.18.1
  logger: ^2.1.0

  # GetX
  get: ^4.6.6

  # Svg
  flutter_svg: ^2.0.10+1

  # Animation
  rive: ^0.13.1

  # kakao login
  kakao_flutter_sdk: ^1.9.0
  kakao_flutter_sdk_user: ^1.9.0

  # Extended Nested Scroll View
  extended_nested_scroll_view: ^6.2.1

  # image_picker
  image_picker: ^1.0.7

  # flutter_secure_storage
  flutter_secure_storage: ^9.0.0

  # Skeleton Animation
  shimmer: ^3.0.0

dev_dependencies:
  # Default
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Localization
  intl_translation: ^0.18.1

  # app icon
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_blue.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/rivs/
    - assets/config/.env
    - assets/thumbnail/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900